version: "3.1"
services:
    mysql:
      image: mysql:8.0
      container_name: bsa-2018-php-13-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=laravel
        - MYSQL_DATABASE=bsa2018php13
        - MYSQL_USER=laravel
        - MYSQL_PASSWORD=secret
      ports:
        - "8082:3306"
    webserver:
      image: nginx:alpine
      container_name: bsa-2018-php-13-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
    php-fpm:
      build: phpdocker/php-fpm
      container_name: bsa-2018-php-13-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini